try verify step3

diff --git a/.github/workflows/scala.yml b/.github/workflows/scala.yml
--- a/.github/workflows/scala.yml
+++ b/.github/workflows/scala.yml
@@ -17,14 +17,6 @@ jobs:
           java-version: 1.8
       - name: Run tests
         run: sbt test
-  check-quality-gates:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-java@v1
-        with:
-          java-version: 1.8
       - name: Check formatting
         run: sbt scalafmtCheckAll
       - name: Run code coverage
@@ -33,9 +25,12 @@ jobs:
         run: bash <(curl -s https://codecov.io/bash)
   create-release:
     if: startsWith(github.ref, 'refs/tags/v')
-    needs: verify-precondition-create-release
+    needs: [build]
     runs-on: ubuntu-latest
     steps:
+      #   If version is v1+ (more accurately not v0+, quick fix) we fail
+      - run: exit 1
+        if: startsWith(github.ref, 'refs/tags/v1')
       - uses: actions/checkout@v2
       - name: Publish locally
         run: sbt publishLocal
@@ -47,10 +42,3 @@ jobs:
         with:
           artifacts: ./techradar
           token: ${{ secrets.GITHUB_TOKEN }}
-  verify-precondition-create-release:
-#   If version is v1+ (more accurately not v0+, quick fix) we fail
-    if: startsWith(github.ref, 'refs/tags/v1')
-    needs: [build, check-quality-gates]
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1
