try verify step

diff --git a/.github/workflows/scala.yml b/.github/workflows/scala.yml
--- a/.github/workflows/scala.yml
+++ b/.github/workflows/scala.yml
@@ -9,7 +9,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          # to also get the tags
+          # also get the tags so git based sbt versioning works
           fetch-depth: 0
       - name: Set up JDK 8
         uses: actions/setup-java@v1
@@ -17,18 +17,7 @@ jobs:
           java-version: 1.8
       - name: Run tests
         run: sbt test
-      # Prepare for release job: transfer artifact
-      - name: Publish locally
-        if: startsWith(github.ref, 'refs/tags/v')
-        run: sbt publishLocal
-      - run: mkdir -p artifacts
-        if: startsWith(github.ref, 'refs/tags/v')
-      - uses: actions/upload-artifact@master
-        if: startsWith(github.ref, 'refs/tags/v')
-        with:
-          name: ivy2
-          path: /home/runner/.ivy2/**
-  quality-gates:
+  check-quality-gates:
     runs-on: ubuntu-latest
     needs: build
     steps:
@@ -42,41 +31,26 @@ jobs:
         run: sbt clean coverage test coverageReport
       - name: Upload to codecov
         run: bash <(curl -s https://codecov.io/bash)
-  build-release-artifacts:
+  create-release:
     if: startsWith(github.ref, 'refs/tags/v')
-    needs: build
+    needs: verify-precondition-create-release
     runs-on: ubuntu-latest
     steps:
-      - run: mkdir -p /home/runner/.ivy2
-      - uses: actions/download-artifact@v2
-        with:
-          name: ivy2
-          path: /home/runner/.ivy2/
+      - uses: actions/checkout@v2
+      - name: Publish locally
+        run: sbt publishLocal
+        # '0.+' will keep on working until 1.x is released
       - run: curl -fLo cs https://git.io/coursier-cli-linux &&
           chmod +x cs &&
           ./cs bootstrap io.github.lhohan::tech-radar-from-csv:0.+ --standalone -o techradar -f
-      - uses: actions/upload-artifact@master
-        with:
-         name: techradar
-         path: ./techradar
       - uses: ncipollo/release-action@v1
         with:
           artifacts: ./techradar
           token: ${{ secrets.GITHUB_TOKEN }}
-#  create-release:
-#    if: startsWith(github.ref, 'refs/tags/v')
-#    needs: [quality-gates, build-release-artifact]
-#    runs-on: ubuntu-latest
-#    steps:
-#      - run: mkdir -p /home/runner/.ivy2
-#      - uses: actions/download-artifact@v2
-#        with:
-#          name: ivy2
-#          path: /home/runner/.ivy2/
-#      - run: curl -fLo cs https://git.io/coursier-cli-linux &&
-#          chmod +x cs &&
-#          ./cs bootstrap io.github.lhohan::tech-radar-from-csv:0.+ --standalone -o techradar -f
-#      - uses: actions/upload-artifact@master
-#        with:
-#          name: techradar
-#          path: ./techradar
+  verify-precondition-create-release:
+#   If version is v1+ (more accurately not v0+, quick fix) we fail
+    if: startsWith(github.ref, 'refs/tags/v1')
+    needs: [build, check-quality-gates]
+    runs-on: ubuntu-latest
+    steps:
+        run: exit 1
