build: Automate release
* Introduces sbt-dynver plugin to get version from git tag
* Hard coded version in main program replaced by generated BuildInfo
* Add release job on push of 'v' tag
* Updated README

diff --git a/.github/workflows/scala.yml b/.github/workflows/scala.yml
--- a/.github/workflows/scala.yml
+++ b/.github/workflows/scala.yml
@@ -6,18 +6,38 @@ on: push
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v2
+        with:
+          # also get the tags so git based sbt versioning works
+          fetch-depth: 0
       - name: Set up JDK 8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - name: Run tests
         run: sbt test
-      - name: Check formatting
-        run: sbt scalafmtCheckAll
-      - name: Run code coverage
-        run: sbt clean coverage test coverageReport
+      # Run quality checks in single step for some speed up
+      - name: Run quality checks
+        run: sbt scalafmtCheckAll coverage test coverageReport
       - name: Upload to codecov
         run: bash <(curl -s https://codecov.io/bash)
+  create-release:
+    if: startsWith(github.ref, 'refs/tags/v')
+    needs: [build]
+    runs-on: ubuntu-latest
+    steps:
+      #   If version is v1+ (more accurately not v0+, quick fix) we fail, coursier step below needs updating
+      - run: exit 1
+        if: startsWith(github.ref, 'refs/tags/v1')
+      - uses: actions/checkout@v2
+      - name: Publish locally
+        run: sbt publishLocal
+        # '0.+' will keep on working until 1.x is released
+      - run: curl -fLo cs https://git.io/coursier-cli-linux &&
+          chmod +x cs &&
+          ./cs bootstrap io.github.lhohan::tech-radar-from-csv:0.+ --standalone -o techradar -f
+      - uses: ncipollo/release-action@v1
+        with:
+          artifacts: ./techradar
+          token: ${{ secrets.GITHUB_TOKEN }}
